
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface SysevcrSymbols {
  /* terminals */
  public static final int GE = 34;
  public static final int STR = 12;
  public static final int CAT = 10;
  public static final int ADD_SYM = 13;
  public static final int GT_SYM = 20;
  public static final int SEMI = 7;
  public static final int INT = 59;
  public static final int LROUND = 37;
  public static final int PRINTLN = 36;
  public static final int CAT_SYM = 11;
  public static final int GE_SYM = 22;
  public static final int CALL_SUPER = 53;
  public static final int RROUND = 38;
  public static final int NOT = 30;
  public static final int AND = 28;
  public static final int LT = 31;
  public static final int AND_SYM = 17;
  public static final int PRIMIF = 44;
  public static final int OBJECT = 49;
  public static final int IN = 6;
  public static final int OR = 29;
  public static final int BOOL = 58;
  public static final int QMARK = 43;
  public static final int COMMA = 9;
  public static final int CALL = 52;
  public static final int CLASS = 47;
  public static final int DIV = 27;
  public static final int IF = 45;
  public static final int DOT = 3;
  public static final int LE = 33;
  public static final int EOF = 0;
  public static final int RETURN = 51;
  public static final int EQUAL = 4;
  public static final int NEW = 50;
  public static final int LAMBDA = 2;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int SUB_SYM = 14;
  public static final int LCURLY = 41;
  public static final int ADD = 24;
  public static final int SEMISEMI = 8;
  public static final int IDENT = 57;
  public static final int VOID = 62;
  public static final int EQ = 35;
  public static final int RCURLY = 42;
  public static final int REAL = 60;
  public static final int ARROW = 54;
  public static final int EMPTYREC = 63;
  public static final int COLON = 56;
  public static final int ELSE = 46;
  public static final int LSQUARE = 39;
  public static final int WEDGE = 55;
  public static final int RSQUARE = 40;
  public static final int LT_SYM = 19;
  public static final int MUL_SYM = 15;
  public static final int LET = 5;
  public static final int EXTENDS = 48;
  public static final int DIV_SYM = 16;
  public static final int STRING = 61;
  public static final int OR_SYM = 18;
  public static final int LE_SYM = 21;
  public static final int GT = 32;
  public static final int EQ_SYM = 23;
  public static final int SUB = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LAMBDA",
  "DOT",
  "EQUAL",
  "LET",
  "IN",
  "SEMI",
  "SEMISEMI",
  "COMMA",
  "CAT",
  "CAT_SYM",
  "STR",
  "ADD_SYM",
  "SUB_SYM",
  "MUL_SYM",
  "DIV_SYM",
  "AND_SYM",
  "OR_SYM",
  "LT_SYM",
  "GT_SYM",
  "LE_SYM",
  "GE_SYM",
  "EQ_SYM",
  "ADD",
  "SUB",
  "MUL",
  "DIV",
  "AND",
  "OR",
  "NOT",
  "LT",
  "GT",
  "LE",
  "GE",
  "EQ",
  "PRINTLN",
  "LROUND",
  "RROUND",
  "LSQUARE",
  "RSQUARE",
  "LCURLY",
  "RCURLY",
  "QMARK",
  "PRIMIF",
  "IF",
  "ELSE",
  "CLASS",
  "EXTENDS",
  "OBJECT",
  "NEW",
  "RETURN",
  "CALL",
  "CALL_SUPER",
  "ARROW",
  "WEDGE",
  "COLON",
  "IDENT",
  "BOOL",
  "INT",
  "REAL",
  "STRING",
  "VOID",
  "EMPTYREC"
  };
}

